In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.06428097,  1.6642728 ,  1.65123365],
       [ 1.77040258,  1.95207613,  0.63857825]])

In [4]:
data * 10

array([[-0.64280972, 16.64272801, 16.51233647],
       [17.70402578, 19.52076126,  6.38578247]])

In [5]:
data + data

array([[-0.12856194,  3.3285456 ,  3.30246729],
       [ 3.54080516,  3.90415225,  1.27715649]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
data1 = [6,7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int32')

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2,3,2))

array([[[1.28863035e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.02018324e-076]],

       [[1.76171512e-076, 8.68847066e-071],
        [2.90255338e-057, 1.15411718e-071],
        [1.27038358e-075, 4.01460140e-057]]])

In [20]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.arange(1,14,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
arr = np.array([1,2,3,4,5])

In [30]:
arr.dtype

dtype('int32')

In [31]:
float_arr = arr.astype(np.float64)

In [32]:
float_arr.dtype

dtype('float64')

In [33]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9])

In [34]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9])

In [35]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12])

In [36]:
numeric_string = np.array(["1.25", "-9.6", "42"])

In [37]:
numeric_string.astype(np.float)

array([ 1.25, -9.6 , 42.  ])

In [38]:
int_array = np.arange(10)

In [39]:
calibers = np.array([.22, .270, .357, .380])

In [40]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
empty_uint32 = np.empty(8, dtype='u4')

In [42]:
empty_uint32

array([1194186128,        607,          0,          0,    7209065,
          6357108,    7471218,          0], dtype=uint32)

In [43]:
arr = np.array([[1,2,3], [4,5,6]])

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
arr2 = np.array([[0,4,1], [7,2,12]])

In [50]:
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [51]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [55]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[5]

5

In [57]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[5:8] = 12

In [59]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [61]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [64]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [65]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [66]:
arr_slice[:] = 64

In [67]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [70]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [72]:
arr2d[2]

array([7, 8, 9])

In [73]:
arr2d[0][2]

3

In [75]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d[0, 2]

3

In [81]:
arr3d = np.arange(1,13).reshape((2,2,3))

In [82]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr3d[0,1]

array([4, 5, 6])

In [86]:
arr3d[0,1,2]

6

In [89]:
old_values = arr3d[0].copy()

In [92]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [93]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [94]:
arr3d[1,0]

array([7, 8, 9])

In [95]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [96]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [97]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [100]:
arr2d[1, :2]

array([4, 5])

In [101]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [104]:
arr2d[:2, 1:]  = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [105]:
names = np.array(['Bob', "Joe", "Will", "Bob", "Will", "Joe", "July"])
data = np.random.randn(7,4)

In [106]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'July'], dtype='<U4')

In [107]:
data

array([[ 0.23942769,  1.7074913 ,  1.64798622, -0.76257147],
       [ 0.56591956,  1.21856266,  0.98987901, -0.1002636 ],
       [-0.79606518, -1.06186136,  2.01971043, -0.22802456],
       [ 1.04147729, -0.9513719 , -0.43948765,  0.00786665],
       [ 0.72634971,  1.70163854,  1.88767558, -0.97823942],
       [ 0.727695  , -0.42907573, -0.00486592, -0.47283414],
       [-0.26487417, -0.45263969,  0.96785535,  0.38503855]])

In [108]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [109]:
data[names == 'Bob']

array([[ 0.23942769,  1.7074913 ,  1.64798622, -0.76257147],
       [ 1.04147729, -0.9513719 , -0.43948765,  0.00786665]])

In [110]:
data[names == 'Bob', 2:]

array([[ 1.64798622, -0.76257147],
       [-0.43948765,  0.00786665]])

In [111]:
data[names == 'Bob', 3]

array([-0.76257147,  0.00786665])

In [112]:
data[~(names == 'Bob')]

array([[ 0.56591956,  1.21856266,  0.98987901, -0.1002636 ],
       [-0.79606518, -1.06186136,  2.01971043, -0.22802456],
       [ 0.72634971,  1.70163854,  1.88767558, -0.97823942],
       [ 0.727695  , -0.42907573, -0.00486592, -0.47283414],
       [-0.26487417, -0.45263969,  0.96785535,  0.38503855]])

In [114]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [115]:
data[mask]

array([[ 0.23942769,  1.7074913 ,  1.64798622, -0.76257147],
       [-0.79606518, -1.06186136,  2.01971043, -0.22802456],
       [ 1.04147729, -0.9513719 , -0.43948765,  0.00786665],
       [ 0.72634971,  1.70163854,  1.88767558, -0.97823942]])

In [118]:
data[data < 0] = 0
data

array([[0.23942769, 1.7074913 , 1.64798622, 0.        ],
       [0.56591956, 1.21856266, 0.98987901, 0.        ],
       [0.        , 0.        , 2.01971043, 0.        ],
       [1.04147729, 0.        , 0.        , 0.00786665],
       [0.72634971, 1.70163854, 1.88767558, 0.        ],
       [0.727695  , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.96785535, 0.38503855]])

In [124]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.56591956, 1.21856266, 0.98987901, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.727695  , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ]])

In [128]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [129]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [130]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [134]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [135]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [138]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [139]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [140]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [141]:
arr = np.random.randn(6,3)
arr

array([[-0.6647328 ,  0.924433  ,  0.7814271 ],
       [-0.86352441,  0.58837116,  0.29954565],
       [-0.47872063, -0.2118261 ,  0.93425555],
       [-0.12394924, -0.4640063 ,  1.10068405],
       [ 0.47264374, -1.53314993,  0.08335863],
       [ 0.84100195,  0.04002505, -0.9774945 ]])

In [142]:
np.dot(arr.T, arr)

array([[ 2.36275735, -1.65462762, -2.14445741],
       [-1.65462762,  3.81307985,  0.02307144],
       [-2.14445741,  0.02307144,  3.74713888]])

In [143]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [144]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [146]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [147]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [148]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [151]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [154]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [156]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.16655975, -0.53409968, -0.09302454, -0.20892766,  0.50494061,
        0.15578011, -1.34832651,  2.27149124])

In [157]:
y

array([-0.44550791, -1.10911679, -2.41011001,  0.73412291,  0.53625465,
       -2.25714311, -0.30414323,  0.70723437])

In [158]:
np.maximum(x, y)

array([-0.16655975, -0.53409968, -0.09302454,  0.73412291,  0.53625465,
        0.15578011, -0.30414323,  2.27149124])

In [159]:
arr = np.random.randn(7) * 5
arr

array([ 5.75420641, 15.13101731, -7.63050855,  2.62339884,  0.19671392,
        0.24792012,  0.42045762])

In [164]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.75420641,  0.13101731, -0.63050855,  0.62339884,  0.19671392,
        0.24792012,  0.42045762])

In [165]:
whole_part

array([ 5., 15., -7.,  2.,  0.,  0.,  0.])

In [171]:
np.sqrt(arr)

F:\my_work\day_20200229\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.3987927 , 3.88986083,        nan, 1.61969097, 0.44352443,
       0.49791577, 0.64842704])

In [172]:
np.sqrt(arr, arr)

F:\my_work\day_20200229\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.3987927 , 3.88986083,        nan, 1.61969097, 0.44352443,
       0.49791577, 0.64842704])

In [184]:
points = np.arange(-5, 5, 0.1)

In [185]:
xs, ys = np.meshgrid(points, points)
xs

array([[-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       ...,
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9]])

In [189]:
np.set_printoptions(suppress=True)

In [193]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [194]:
z

array([[7.07106781, 7.00071425, 6.93108938, ..., 6.86221539, 6.93108938,
        7.00071425],
       [7.00071425, 6.92964646, 6.85930026, ..., 6.78969808, 6.85930026,
        6.92964646],
       [6.93108938, 6.85930026, 6.7882251 , ..., 6.71788657, 6.7882251 ,
        6.85930026],
       ...,
       [6.86221539, 6.78969808, 6.71788657, ..., 6.64680374, 6.71788657,
        6.78969808],
       [6.93108938, 6.85930026, 6.7882251 , ..., 6.71788657, 6.7882251 ,
        6.85930026],
       [7.00071425, 6.92964646, 6.85930026, ..., 6.78969808, 6.85930026,
        6.92964646]])

In [195]:
import matplotlib.pyplot as plt

In [207]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

In [211]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.show()

In [209]:
plt.show()

In [213]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [214]:
cond = np.array([True, False, True, True, False])

In [218]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [216]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [220]:
arr = np.random.randn(4, 4)
arr

array([[-1.71413204,  1.06617687,  1.0641011 ,  0.56190459],
       [ 0.64112152,  0.65275916, -1.18503512, -1.29577355],
       [-0.93479911,  0.3346763 , -1.03740957, -0.04579191],
       [-0.30687265,  0.61961522,  2.2808282 ,  0.0658938 ]])

In [221]:
arr > 0

array([[False,  True,  True,  True],
       [ True,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [224]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2,  2],
       [ 2,  2, -2, -2],
       [-2,  2, -2, -2],
       [-2,  2,  2,  2]])

In [225]:
np.where(arr > 0, 2, arr)

array([[-1.71413204,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        , -1.18503512, -1.29577355],
       [-0.93479911,  2.        , -1.03740957, -0.04579191],
       [-0.30687265,  2.        ,  2.        ,  2.        ]])

In [226]:
arr = np.random.randn(5, 4)
arr

array([[-0.64537855,  0.66083148, -0.31571466,  1.40446448],
       [-0.02313959,  0.4075175 ,  0.02426757, -1.60034299],
       [ 1.08969211,  0.1824835 , -0.81198076, -0.15644817],
       [ 1.07925754, -0.04504799,  0.04606472, -0.18087412],
       [-1.67175682,  0.98507979, -0.87512776,  1.04704793]])

In [227]:
arr.mean()

0.030044761560820688

In [228]:
np.mean(arr)

0.030044761560820688

In [229]:
arr.sum()

0.6008952312164137

In [230]:
np.sum(arr)

0.6008952312164137

In [231]:
arr.mean(axis=1)

array([ 0.27605069, -0.29792438,  0.07593667,  0.22485004, -0.12868921])

In [232]:
arr.sum(axis=0)

array([-0.17132532,  2.1908643 , -1.93249088,  0.51384713])

In [233]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [234]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [235]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [236]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [237]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [238]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [241]:
arr = np.random.randn(100)
arr

array([ 0.49605339,  0.18545734, -1.51821186,  0.89309696,  1.8986749 ,
        0.30763318, -1.70427753,  2.05791538, -0.15487752, -0.38296491,
        0.94566239,  1.1190992 ,  0.34762693, -0.55770836,  0.79241538,
        0.30230791, -1.61898917, -1.34670117, -0.40490022, -0.61188709,
        1.48757106, -0.4140651 ,  0.39212648,  0.11924595, -0.50095463,
       -0.36393496, -0.3598986 , -0.51057372, -0.95414336,  0.38138693,
        0.35191101,  1.56023295,  0.6063374 , -0.45944496, -0.48369572,
       -0.18249027, -1.46697631, -0.21305272,  0.12534293,  0.58323573,
       -0.90053914,  0.42164611,  0.20330343,  2.10354087, -0.0085852 ,
       -0.58424301, -0.81735799,  1.78229766,  0.21518504, -0.45400454,
        0.04168762, -0.57121737, -0.46053464, -0.31451292, -0.63250507,
        0.2961323 ,  1.6713276 , -0.03515237, -0.81685555,  0.54177185,
        1.37547954,  1.33145049,  1.05415237,  0.57386764,  0.60751151,
       -0.32715646,  2.32312376, -0.29323771, -1.54252011, -1.47

In [243]:
(arr > 0).sum()

49

In [245]:
bools = np.array([False, False, True, False])
bools

array([False, False,  True, False])

In [246]:
bools.any()

True

In [247]:
bools.all()

False

In [249]:
arr = np.random.randn(6)
arr

array([ 1.73281831,  1.21922953, -0.74230272, -0.81088828, -0.00804944,
       -1.01367133])

In [251]:
arr.sort()
arr

array([-1.01367133, -0.81088828, -0.74230272, -0.00804944,  1.21922953,
        1.73281831])

In [252]:
arr = np.random.randn(5, 3)
arr

array([[ 1.63126161,  0.24320057, -1.03375207],
       [-0.39798323,  1.07268853, -0.92712817],
       [-0.35391187,  1.32632429,  0.48596048],
       [-0.23006935,  0.65709241,  0.2155195 ],
       [-0.170814  , -0.28119808,  0.40715981]])

In [255]:
arr.sort(axis=1)
arr

array([[-1.03375207,  0.24320057,  1.63126161],
       [-0.92712817, -0.39798323,  1.07268853],
       [-0.35391187,  0.48596048,  1.32632429],
       [-0.23006935,  0.2155195 ,  0.65709241],
       [-0.28119808, -0.170814  ,  0.40715981]])

In [256]:
large_arr = np.random.randn(1000)

In [259]:
large_arr.sort()

In [260]:
large_arr[int(0.05 * len(large_arr))]

-1.6843548984533585

In [261]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [262]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [263]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [264]:
np.unique(ints)

array([1, 2, 3, 4])

In [265]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [266]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## 用于数组的文件输入输出

In [267]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [268]:
np.save("some_array", arr)

In [272]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
np.savez("array_archive", a=arr, b=arr)

In [277]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [285]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [286]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [287]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [288]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [289]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [291]:
x @ np.ones(3)

array([ 6., 15.])

In [293]:
from numpy.linalg import inv, qr

In [294]:
x = np.random.randn(5, 5)
x

array([[-0.04885162, -0.21846884, -1.24292805, -0.60608414,  1.26510266],
       [-1.49299244,  1.21760754,  0.61608657,  0.69090052,  0.80898191],
       [-0.60451624, -0.4953847 , -0.45726043,  0.50449917, -0.16310962],
       [ 0.55467914,  1.36399657, -0.1306418 ,  0.25394491, -0.15353725],
       [-0.42525257, -0.17885288,  0.74059119, -1.36711435,  1.51748628]])

In [296]:
mat = x.T.dot(x)
mat

array([[ 3.0853615 , -0.67510011, -0.97007479, -0.58465217, -1.90148263],
       [-0.67510011,  3.66817775,  0.93756069,  1.31462733,  0.30860791],
       [-0.97007479,  0.93756069,  2.6990625 , -0.09736266,  0.14445023],
       [-0.58465217,  1.31462733, -0.09736266,  3.03269059, -2.40368857],
       [-1.90148263,  0.30860791,  0.14445023, -2.40368857,  4.60787952]])

In [297]:
inv(mat)

array([[ 56.40893722, -29.31258925,  29.76429639,  74.67957383,
         63.26417365],
       [-29.31258925,  15.71032709, -15.63478144, -39.20559484,
        -33.10965542],
       [ 29.76429639, -15.63478144,  16.13532624,  39.54946619,
         33.45468508],
       [ 74.67957383, -39.20559484,  39.54946619,  99.76276159,
         84.24411883],
       [ 63.26417365, -33.10965542,  33.45468508,  84.24411883,
         71.43800449]])

In [298]:
mat.dot(inv(mat))

array([[ 1., -0., -0.,  0., -0.],
       [ 0.,  1.,  0., -0., -0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [-0.,  0., -0., -0.,  1.]])

In [299]:
q, r = qr(mat)

In [300]:
r

array([[-3.85664559,  1.7694733 ,  1.6755539 , -0.05200987,  3.51904546],
       [ 0.        , -3.6718873 , -0.97396964, -2.30475286,  1.47434615],
       [ 0.        ,  0.        , -2.31932127,  0.54463641,  0.4470894 ],
       [ 0.        ,  0.        ,  0.        , -3.38278791,  3.99808611],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.00736844]])

In [303]:
np.linalg.eig(x)

(array([ 2.18224105+0.j        ,  0.98319426+1.35553232j,
         0.98319426-1.35553232j, -1.57162122+0.j        ,
        -0.09408166+0.j        ]),
 array([[ 0.47903519+0.j        , -0.33131954+0.41219j   ,
         -0.33131954-0.41219j   , -0.56611294+0.j        ,
          0.44808929+0.j        ],
        [-0.63931194+0.j        , -0.32926767+0.01002005j,
         -0.32926767-0.01002005j, -0.33276582+0.j        ,
         -0.26187455+0.j        ],
        [-0.08595858+0.j        ,  0.14991781-0.1775472j ,
          0.14991781+0.1775472j , -0.60187478+0.j        ,
          0.26701877+0.j        ],
        [-0.34711408+0.j        , -0.01912802+0.39962221j,
         -0.01912802-0.39962221j,  0.39627726+0.j        ,
          0.63544149+0.j        ],
        [ 0.48366152+0.j        , -0.63067188+0.j        ,
         -0.63067188-0.j        ,  0.22247279+0.j        ,
          0.5055223 +0.j        ]]))

In [308]:
samples = np.random.normal(size=(4, 4))
samples

array([[-1.04607585,  0.47490437,  0.04585558, -0.18155867],
       [-1.55436425,  0.2609112 , -1.05048491, -0.67510963],
       [-1.20172085,  0.20472312, -1.91484195,  0.03558294],
       [-2.10626031,  2.44034049,  1.88518745,  1.13144623]])

In [309]:
np.random.seed(1234)

In [313]:
rng = np.random.RandomState(1234)

In [314]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [324]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

In [329]:
plt.plot(walk[:100])
plt.show()

In [335]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)

In [337]:
steps = np.where(draws>0, 1, -1)

array([ 1, -1,  1, -1,  1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1,  1,
       -1,  1, -1])

In [340]:
walk = steps.cumsum()

In [341]:
walk.min()

-27

In [342]:
walk.max()

26

In [346]:
(np.abs(walk) >= 10).argmax()

55

In [347]:
nwalks = 5000
nsteps = 1000

In [351]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)

In [355]:
walks = steps.cumsum(axis=1)
walks

array([[ -1,  -2,  -3, ..., -12, -11, -12],
       [  1,   0,  -1, ..., -30, -31, -30],
       [  1,   0,  -1, ..., -10, -11, -10],
       ...,
       [  1,   2,   1, ...,  32,  31,  30],
       [  1,   2,   1, ...,  12,  13,  14],
       [  1,   0,   1, ..., -28, -27, -26]], dtype=int32)

In [357]:
walks.max()

115

In [358]:
walks.min()

-138

In [390]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30

array([ True,  True,  True, ...,  True,  True, False])

In [391]:
hits30.shape

(5000,)

In [392]:
hits30.sum()

3467

In [380]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis = 1)
crossing_times

array([759, 417, 331, ..., 731, 655, 917], dtype=int64)

In [381]:
crossing_times.mean()

498.68906835881165